coverage:
  status:
    project:
      default:
        threshold: 1.0
ignore:
  - "example-apps"
  - "hapi"
  - "hedera-node/cli-clients"
  - "hedera-node/test-clients"
  - "platform-sdk/platform-apps"
