release:
  branching:
    execution:
      time: "22:00:00"
    schedule:
      - on: "2024-05-06"
        name: release/0.50
        initial-tag:
          create: true
          name: v0.50.0-alpha.0

