#name: JavaDoc
#
#on:
#  pull_request:
#    branches: [ $default-branch, release/** ]
#  push:
#    branches: [ $default-branch, release/** ]
#    tags: [ v* ]
#
#jobs:
#  JavaDoc:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build Project
#        run: ./mvnw clean install -DskipTests
#      - name: Generate javadocs
#        run: ./mvnw javadoc:javadoc
