##
# Copyright (C) 2023-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: CITR Extended CI Tests
on:
  schedule:
    # Runs Extended Test Suite every three hours
    - cron: '0 */3 * * *'

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  GRADLE_CACHE_USERNAME: ${{ secrets.gradle-cache-username }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.gradle-cache-password }}
  GRADLE_EXEC: ionice -c 2 -n 2 nice -n 19 ./gradlew
  XTS_CANDIDATE_TAG: "xts-candidate"

jobs:
  extended-test-suite:
    name: eXtended Test Suite
    runs-on: network-node-linux-medium

    steps:
      # Checkout the latest from dev
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # Check if the xts-candidate tag exists
      - name: Check for tags
        id: check_tags_exist
        run: |
          TAG=${XTS_CANDIDATE_TAG}
          if [ $(git tag -l "${TAG}") ]; then
            echo "xts_tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "xts_tag_exists=false" >> $GITHUB_OUTPUT
          fi

      # If no xts-candidate tag exists error out and exit the workflow
      - name: No Tags Found
        if: ${{ steps.check_tags_exist.outputs.xts_tag_exists == 'false' }}
        run: |
          echo "No XTS tags found. Ending CITR check.
          exit 1

      # Checkout the tagged reference
      - name: Checkout Tagged Code
        id: checkout_tagged_code
        if: ${{ steps.check_tags_exist.outputs.xts_tag_exists == 'true' }}
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: '${XTS_CANDIDATE_TAG}'

      # Remove the tag so other jobs can be promoted to xts-candidate status
      - name: Remove xts-candidate tag
        run: |
          git tag -d ${XTS_CANDIDATE_TAG}
          git push --delete origin ${XTS_CANDIDATE_TAG}

      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          cache-read-only: false

      - name: Setup NodeJS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20

      # prepare to run eXtended Test Suite
      - name: Compile
        id: gradle-build
        run: ${GRADLE_EXEC} assemble :test-clients:yahCliJar --scan

      - name: Timing Sensitive Tests
        id: gradle-timing-sensitive
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        run: ${GRADLE_EXEC} timingSensitive --continue --scan

      - name: Publish Unit Test (Timing Sensitive) Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Timing Sensitive Unit Test Results'
          json_thousands_separator: ','
          junit_files: "**/build/test-results/timingSensitive/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: Time Consuming Tests
        id: gradle-time-consuming
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        run: ${GRADLE_EXEC} timeConsuming --continue --scan

      - name: Publish Unit Test (Time Consuming) Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Time Consuming Unit Test Results'
          json_thousands_separator: ','
          junit_files: "**/build/test-results/timeConsuming/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: Hammer Tests
        id: gradle-hammer-tests
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        run: ${GRADLE_EXEC} hammer --continue --scan

      - name: Publish Hammer Test Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Hammer Test Results'
          json_thousands_separator: ','
          junit_files: "**/build/test-results/hammer/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: HAPI Testing (Time Consuming)
        id: gradle-hapi-time-consuming
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        env:
          LC_ALL: en.UTF-8
          LANG: en_US.UTF-8
        run: ${GRADLE_EXEC} hapiTestTimeConsuming --scan

      - name: Publish HAPI Test (Time Consuming) Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: HAPI Test (Time Consuming) Results'
          json_thousands_separator: ','
          junit_files: "**/test-clients/build/test-results/test/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: Upload HAPI Test (Time Consuming) Network Logs
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        # if: ${{ inputs.enable-hapi-tests-time-consuming && inputs.enable-network-log-capture && steps.gradle-hapi-time-consuming.conclusion == 'failure' && !cancelled() }}
        if: ${{ steps.gradle-hapi-time-consuming.conclusion == 'failure' && !cancelled() }}
        with:
          name: HAPI Test (Time Consuming) Network Logs
          path: |
            hedera-node/test-clients/build/hapi-test/**/output/**
          retention-days: 7

      # Report failure if XTS failed.
      - name: Report XTS failure
        if: ${{ steps.gradle-timing-sensitive.conclusion == 'failure' ||
          steps.gradle-time-consuming.conclusion == 'failure' ||
          steps.gradle-hammer-tests.conclusion == 'failure' ||
          steps.gradle-hapi-time-consuming.conclusion == 'failure' }}
        run: |
          echo "eXtended Test Suite failed during execution."
          exit 2

      # Now that the XTS suite has run we should be able to tag for promotion
      - name: Tag for XTS promotion
        if: ${{ steps.gradle-timing-sensitive.conclusion == 'success' &&
                steps.gradle-time-consuming.conclusion == 'success' &&
                steps.gradle-hammer-tests.conclusion == 'success' &&
                steps.gradle-hapi-time-consuming.conclusion == 'success' }}
        run: |
          EPOCH_TIME=`date -j -f "%a %b %d %T %Z %Y" "\`LC_ALL=C date\`" "+%s"`
          TAG=xts-pass-${EPOCH_TIME}
          git tag --annotate ${TAG}
          git push --set-upstream origin --tags
