##
# Copyright (C) 2023-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: CITR Extended CI Tests
on:
  schedule:
    # Runs Extended Test Suite every three hours
    - cron: '0 */3 * * *'

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  GRADLE_CACHE_USERNAME: ${{ secrets.gradle-cache-username }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.gradle-cache-password }}
  GRADLE_EXEC: ionice -c 2 -n 2 nice -n 19 ./gradlew

jobs:
  extended-test-suite:
    name: eXtended Test Suite
    runs-on: network-node-linux-medium

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          cache-read-only: false

      - name: Setup NodeJS
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20

      - name: Compile
        id: gradle-build
        run: ${GRADLE_EXEC} assemble :test-clients:yahCliJar --scan

      - name: Timing Sensitive Tests
        id: gradle-timing-sensitive
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        run: ${GRADLE_EXEC} timingSensitive --continue --scan

      - name: Publish Unit Test (Timing Sensitive) Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ inputs.enable-unit-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Timing Sensitive Unit Test Results'
          json_thousands_separator: ','
          junit_files: "**/build/test-results/timingSensitive/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: Time Consuming Tests
        id: gradle-time-consuming
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        run: ${GRADLE_EXEC} timeConsuming --continue --scan

      - name: Publish Unit Test (Time Consuming) Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Time Consuming Unit Test Results'
          json_thousands_separator: ','
          junit_files: "**/build/test-results/timeConsuming/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: Hammer Tests
        id: gradle-hammer-tests
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        run: ${GRADLE_EXEC} hammer --continue --scan

      - name: Publish Hammer Test Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: Hammer Test Results'
          json_thousands_separator: ','
          junit_files: "**/build/test-results/hammer/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: HAPI Testing (Time Consuming)
        id: gradle-hapi-time-consuming
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        env:
          LC_ALL: en.UTF-8
          LANG: en_US.UTF-8
        run: ${GRADLE_EXEC} hapiTestTimeConsuming --scan

      - name: Publish HAPI Test (Time Consuming) Report
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        if: ${{ steps.gradle-build.conclusion == 'success' && !cancelled() }}
        with:
          check_name: 'Node: HAPI Test (Time Consuming) Results'
          json_thousands_separator: ','
          junit_files: "**/test-clients/build/test-results/test/TEST-*.xml"
          comment_mode: errors # only comment if we could not find or parse the JUnit XML files

      - name: Upload HAPI Test (Time Consuming) Network Logs
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        # if: ${{ inputs.enable-hapi-tests-time-consuming && inputs.enable-network-log-capture && steps.gradle-hapi-time-consuming.conclusion == 'failure' && !cancelled() }}
        if: ${{ steps.gradle-hapi-time-consuming.conclusion == 'failure' && !cancelled() }}
        with:
          name: HAPI Test (Time Consuming) Network Logs
          path: |
            hedera-node/test-clients/build/hapi-test/**/output/**
          retention-days: 7

  tag:
    name: Tag for promotion / release
    runs-on: network-node-linux-medium

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Add BuildID Tag
        run: echo "Add Build Identifier"

      - name: Add Promotion Tag
        run: echo "Add promotion tag"
