name: PR Assignee and Milestone Check

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check_pr:
    runs-on: [self-hosted, Linux, medium, ephemeral]

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      - name: Install dependencies
        run: npm install axios

      - name: Check PR assignees and milestones
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
        run: node .github/scripts/check-pr.js
